from __future__ import annotations

import json
from typing import Any


SYSTEM_PROMPT = """
You generate concise descriptions for an AI tools directory.

Rules:
1. Use ONLY the supplied evidence.
2. Never invent features, pricing, integrations, platforms, companies,
   performance claims, or capabilities.
3. Do not copy the source description verbatim.
4. Write one concise, specific description in 1-2 sentences.
5. Clearly explain what the tool does and its primary use case when supported.
6. If evidence is limited, keep the description conservative.
7. If there is no usable evidence, return an empty description.
8. Do not mention that the description was generated by an AI.
9. Do not include promotional language such as "best", "leading", or
   "revolutionary" unless it is essential to the factual identity of the tool.
"""


def build_description_prompt(record: dict[str, Any]) -> str:
    evidence = {
        "name": record.get("name"),
        "official_url": record.get("official_url"),
        "source_quality": record.get("source_quality"),
        "official_description": record.get("official_description"),
        "headings": record.get("headings", []),
        "paragraphs": record.get("paragraphs", []),
    }

    return (
        "Generate a concise factual description for this AI tool.\n\n"
        "Evidence:\n"
        f"{json.dumps(evidence, ensure_ascii=False, indent=2)}"
    )